from pathlib import Path


class PyLockInterface:
    """Suite interface"""

    @property
    def random_enc_key() -> str: ...

    def save_keyfile(self, key, path: Path): ...

    def write_file(self, path: Path, data: str, mode: str): ...

    def read_file(self, path: Path): ...

    def encrypt(self, data: str, key: str | bytes, cipher) -> str: ...

    def decrypt(self, data: str, key: str | bytes, cipher) -> str: ...

    def write_metadata(self, data: str | bytes): ...

    def process_file(self, path: Path, key: str | bytes): ...

    def process_dir(self, path: Path, key: str | bytes): ...

    def read_encryption_info(self, path: Path) -> dict: ...

    def is_encrypted(self, path: Path) -> bool: ...

    def passphrase_to_key(self, passphrase: str, salt: str) -> str: ...

    def guess_cipher(self, info: dict): ...


class LockInterface:
    """Lock manager interface"""

    def lock(self, path: Path, pid: int): ...
    def unlock(self, path: Path, pid: int): ...
    def is_locked(self, path: Path): ...
    def get_lock_pid(self, path: Path): ...


class Ciphers:
    """All cipher must implement"""

    def encrypt(self, data: str) -> str: ...
    def decrypt(self, data: str) -> str: ...
    def is_data_compartible(self, data: str | bytes) -> bool: ...
